# Generated by Django 4.0.3 on 2022-03-29 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('size', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('weekly_rate', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('monthly_rate', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('utility_conversion_rate', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('is_active', models.BooleanField()),
                ('cancellation_penalty', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('cancellation_time_window', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField()),
                ('parking_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_spot', to='adminhome.parkingcategory')),
            ],
        ),
    ]
