# Generated by Django 4.0.3 on 2022-04-16 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminhome', '0002_billdetail_payment_vehicle_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.CharField(choices=[('new', 'New Booking'), ('pending', 'Pending Approval'), ('pending_lease', 'Pending Lease'), ('rejected', 'Rejected Booking'), ('approved', 'Approved Booking'), ('canceled_before_lease', 'Canceled Before Lease'), ('canceled', 'Canceled Booking'), ('paid', 'Paid Booking'), ('unpaid', 'Unpaid Booking')], default='new', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
