# Generated by Django 4.0.3 on 2022-04-16 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminhome', '0003_vehicle_user_id_alter_booking_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
