# Generated by Django 4.0.3 on 2022-04-17 23:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0004_alter_vehicle_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='build',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_doc',
            field=models.FileField(default='default', upload_to='insurance/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 23, 15, 34, 811085, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
