# Generated by Django 4.0.3 on 2022-04-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0005_vehicle_build_vehicle_color_vehicle_insurance_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
