# Generated by Django 4.0.3 on 2022-04-19 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0007_remove_booking_bill_detail_id_billdetail_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='parking_spot_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='adminhome.parkingspot'),
        ),
    ]
