# Generated by Django 4.0.3 on 2022-04-19 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0008_alter_booking_parking_spot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='parking_spot_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='adminhome.parkingspot'),
        ),
    ]
