# Generated by Django 4.0.3 on 2022-04-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0010_alter_booking_pc_id_alter_booking_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateField(),
        ),
    ]
