# Generated by Django 4.0.3 on 2022-04-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0011_alter_booking_end_time_alter_booking_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
