# Generated by Django 4.0.3 on 2022-04-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0012_alter_booking_end_time_alter_booking_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetail',
            name='end_meter_reading',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='init_meter_reading',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='meter_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='misc_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='reservation_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='utility_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
