# Generated by Django 4.0.3 on 2022-04-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0014_remove_billdetail_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetail',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
