# Generated by Django 4.0.3 on 2022-04-25 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminhome', '0019_booking_bk_creation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bk_last_modified_username',
            field=models.ForeignKey(default=38, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
