# Generated by Django 4.0.3 on 2022-04-25 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0020_booking_bk_last_modified_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bk_creation_time',
            new_name='creation_time',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='bk_last_modified_time',
            new_name='last_modified_time',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='bk_last_modified_username',
            new_name='last_modified_userid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='bk_lease_signed_time',
        ),
    ]
