# Generated by Django 4.0.3 on 2022-04-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0021_rename_bk_creation_time_booking_creation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.CharField(choices=[('new', 'New Booking'), ('pending_approval', 'Pending Approval'), ('pending_lease', 'Pending Lease'), ('pending_slot', 'Pending Slot'), ('rejected', 'Rejected Booking'), ('approved', 'Approved Booking'), ('canceled_before_lease', 'Canceled Before Lease'), ('canceled', 'Canceled Booking'), ('paid', 'Paid Booking')], default='new', max_length=30),
        ),
    ]
