# Generated by Django 4.0.3 on 2022-12-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0022_alter_booking_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_one', models.CharField(max_length=60)),
                ('option_two', models.CharField(max_length=60)),
                ('option_three', models.CharField(max_length=60)),
                ('options_one_count', models.IntegerField(default=0)),
                ('options_two_count', models.IntegerField(default=0)),
                ('options_three_count', models.IntegerField(default=0)),
            ],
        ),
    ]
